### ISSUE TITLE
Which data structures may RcppArrayFire return?

### ISSUE THREAD

**Issue by JordiMolinsCoronado** [RInstitute/rcpparrayfire#10]
The examples at http://gallery.rcpp.org/articles/introducing-rcpparrayfire/ are very informative, and well written.

One question I have is: which kind of data structures may RcppArrayFire return? 

In the examples, the considered function, such as the put pricer, always returns a scalar. Then, if one needs to use several vector inputs, something like "within(options, p <- put_option_pricer_af(s, k, r, y, t, sigma))" works nicely.

But what happens if:

1. The considered function (my analogous to the put pricer) is not a combination of already-AF-vectorized functions, such as log or sqrt? I understand that the package has an af::log function, and this function understands that once it receives an array, it has to send the individual components of the array to different cores of the GPU, and do the log calculation there, individually. But what happens if my function is not composed of this kind of already-AF-vectorized functions? How can I AF-vectorize my function?

2. I need to return a vector/matrix/3d-array, not a scalar, from my function. Is the AF-array data structure able to handle with these cases? I see in the code of the package that there is something like array4d, but I do not know if this array4d has anything to do with this question (2)

Thank you for this great package.

**Comment by JordiMolinsCoronado** [comment]
For example: 

instead of the code snippet of the example quoted above:

// [[Rcpp::export]]
array put_option_pricer_af(RcppArrayFire::typed_array<f32> s,
                           RcppArrayFire::typed_array<f32> k, 
                           RcppArrayFire::typed_array<f32> r, 
                           RcppArrayFire::typed_array<f32> y, 
                           RcppArrayFire::typed_array<f32> t, 
                           RcppArrayFire::typed_array<f32> sigma) {
  
  array d1 = (log(s / k) + (r - y + sigma * sigma / 2.0) * t) / (sigma * sqrt(t));
  array d2 = d1 - sigma * sqrt(t);
  
  return normcdf(-d2) * k * exp(-r * t) - s * exp(-y * t) * normcdf(-d1); 
}

is it possible to do something like:

// [[Rcpp::export]]
array put_option_pricer_af(RcppArrayFire::typed_array<f32> s,
                           RcppArrayFire::typed_array<f32> k, 
                           RcppArrayFire::typed_array<f32> r, 
                           RcppArrayFire::typed_array<f32> y, 
                           RcppArrayFire::typed_array<f32> t, 
                           RcppArrayFire::typed_array<f32> sigma) {
  
  array d1 = (log(s / k) + (r - y + sigma * sigma / 2.0) * t) / (sigma * sqrt(t));
  array d2;
  for(int i = 0; i < d2.size(); i++) {d2(i) = my_function(sigma(i), t(i));}
  
  return normcdf(-d2) * k * exp(-r * t) - s * exp(-y * t) * normcdf(-d1); 
}

such that my_function is a generic (in the sense of not-AF) function that I can define without using af::log and similar functions.

**Comment by JordiMolinsCoronado** [comment]
Edit to the two comments above:

I have been checking the documentation of ArrayFire, and I see most of my questions are answered there. For example, batchFun in http://arrayfire.org/docs/vectorization.htm is able to vectorize "my_fun":

http://arrayfire.org/docs/vectorization.htm

And also there are up to 4-dimensional arrays.

And ArrayFire has even linear algebra, including a linear solver, which is basically all I need from linear algebra.

So, my questions above can be rephrased as: can all the functionality in ArrayFire be used in RcppArrayFire? Or are there limitations?

**Comment by rstub** [comment]
Yes, you can use all the functionality from ArrayFire via RcppArrayFire. That’s the point of the package ;-)

**Comment by JordiMolinsCoronado** [comment]
Good, thank you!

Is there some kind of wrapper to transform an AF array into a say Rcpp
NumericVector?

**Comment by rstub** [comment]
RcppArrayFire provides extensions to `Rcpp::as<>` and `Rcpp::wrap`. This way you can easily convert an `af::array` into an `SEXP` and back. And from an `SEXP` it is easy to create the Rcpp data types, e.g.:

```
// [[Rcpp::depends(RcppArrayFire)]]
#include <RcppArrayFire.h>

// [[Rcpp::export]]
Rcpp::NumericMatrix squareMatrix(RcppArrayFire::typed_array<f32> x) {
    af::array y = af::matmulTN(x ,x);
    Rcpp::NumericMatrix _y(Rcpp::wrap(y));
    return _y;
}

/*** R
set.seed(42)
N <- 40
X <- matrix(rnorm(N * N * 2), ncol = N)
tXXR <- t(X) %*% X
tXXGPU <- squareMatrix(X)

all.equal(tXXR, tXXGPU)
*/

```

**Comment by ilovericenoodle** [comment]
Hello,

Thank you for this amazing package! I am trying to build a package with RcppArrayFire. However, I also want to return an af:array as the function output. I tried building a package by
` 
    RcppArrayFire.package.skeleton("ex", example_code = FALSE)
`
`
    install.packages("ex", repos = NULL, type = "source")
`
where "ex“ is the package name and I created a CPP file in the ex/src with the code in the quoted comment. However, I receive the following error:

`Installing package into ‘/home/wzhou/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘ex’ ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Wall -I'/home/wzhou/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include' -I'/home/wzhou/R/x86_64-pc-linux-gnu-library/4.0/RcppArrayFire/include'   -I../inst/include -I'/home/wzhou/document/arrayfire/include' -fpic  -g -O2 -fdebug-prefix-map=/home/jranke/git/r-backports/buster/r-base-4.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ex.cpp -o ex.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-z,relro -o ex.so ex.o -llapack -lblas -lgfortran -lm -lquadmath -L/home/wzhou/document/arrayfire/lib64 -lafcuda -L/usr/lib/R/lib -lR
installing to /home/wzhou/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-ex/00new/ex/libs
** help
Warning: /home/wzhou/script/ex/man/ex-package.Rd:27: All text must be in a section
Warning: /home/wzhou/script/ex/man/ex-package.Rd:28: All text must be in a section
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘ex’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/wzhou/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-ex/00new/ex/libs/ex.so':
  /home/wzhou/R/x86_64-pc-linux-gnu-library/4.0/00LOCK-ex/00new/ex/libs/ex.so: undefined symbol: _ZN4Rcpp4wrapIN2af5arrayEEEP7SEXPRECRKT_
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/wzhou/R/x86_64-pc-linux-gnu-library/4.0/ex’
Warning message:
In install.packages("ex", repos = NULL, type = "source") :
  installation of package ‘ex’ had non-zero exit status`

I notice that there is a function called wrap_array in the RcppArrayFireWrap.h. So I tried replacing Rcpp::wrap with this function. Below is my source code:

`
    // [[Rcpp::depends(RcppArrayFire)]]
    #include "RcppArrayFire.h"
    // [[Rcpp::export]]
    Rcpp::NumericMatrix squareMatrix(RcppArrayFire::typed_array<f32> x) {
    const af::array y = af::matmulTN(x ,x);
    Rcpp::NumericMatrix _y(RcppArrayFire::wrap_array<(af_dtype)0>(y));
    return _y;
    }
`
Building this code I got:
`
Installing package into ‘/home/wzhou/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘ex’ ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -Wall -I'/home/wzhou/R/x86_64-pc-linux-gnu-library/4.0/Rcpp/include' -I'/home/wzhou/R/x86_64-pc-linux-gnu-library/4.0/RcppArrayFire/include'   -I../inst/include -I'/home/wzhou/document/arrayfire/include' -fpic  -g -O2 -fdebug-prefix-map=/home/jranke/git/r-backports/buster/r-base-4.0.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c ex.cpp -o ex.o
ex.cpp: In function ‘Rcpp::NumericMatrix squareMatrix(RcppArrayFire::typed_array<(af_dtype)0>)’:
ex.cpp:6:68: error: no matching function for call to ‘wrap_array<(af_dtype)0>(const af::array&)’
     Rcpp::NumericMatrix _y(RcppArrayFire::wrap_array<(af_dtype)0>(y));
                                                                    ^
In file included from /home/wzhou/R/x86_64-pc-linux-gnu-library/4.0/RcppArrayFire/include/RcppArrayFire.h:31,
                 from ex.cpp:2:
/home/wzhou/R/x86_64-pc-linux-gnu-library/4.0/RcppArrayFire/include/RcppArrayFireWrap.h:131:31: note: candidate: ‘template<class T> SEXPREC* RcppArrayFire::wrap_array(const af::array&)’
     template<typename T> SEXP wrap_array( const af::array& object ){
                               ^~~~~~~~~~
/home/wzhou/R/x86_64-pc-linux-gnu-library/4.0/RcppArrayFire/include/RcppArrayFireWrap.h:131:31: note:   template argument deduction/substitution failed:
make: *** [/usr/lib/R/etc/Makeconf:181: ex.o] Error 1
ERROR: compilation failed for package ‘ex’
`

Could you please give me some hints about what I am doing wrong? Many thanks!

> RcppArrayFire provides extensions to `Rcpp::as<>` and `Rcpp::wrap`. This way you can easily convert an `af::array` into an `SEXP` and back. And from an `SEXP` it is easy to create the Rcpp data types, e.g.:
> 
> ```
> // [[Rcpp::depends(RcppArrayFire)]]
> #include <RcppArrayFire.h>
> 
> // [[Rcpp::export]]
> Rcpp::NumericMatrix squareMatrix(RcppArrayFire::typed_array<f32> x) {
>     af::array y = af::matmulTN(x ,x);
>     Rcpp::NumericMatrix _y(Rcpp::wrap(y));
>     return _y;
> }
> 
> /*** R
> set.seed(42)
> N <- 40
> X <- matrix(rnorm(N * N * 2), ncol = N)
> tXXR <- t(X) %*% X
> tXXGPU <- squareMatrix(X)
> 
> all.equal(tXXR, tXXGPU)
> */
> ```
