### ISSUE TITLE
Installation / Ubuntu 16.04

### ISSUE THREAD

**Issue by theogrost** [RInstitute/rcpparrayfire#4]
Hi,
first thing: great project ;)
second: I can't install it.
While trying to do so, I get:
```
installing to /home/theogrost/R/x86_64-pc-linux-gnu-library/3.4/RcppArrayFire/libs
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘RcppArrayFire’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/theogrost/R/x86_64-pc-linux-gnu-library/3.4/RcppArrayFire/libs/RcppArrayFire.so':
  libaf.so.3: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/theogrost/R/x86_64-pc-linux-gnu-library/3.4/RcppArrayFire’
Installation failed: Command failed (1)
```

**Comment by rstub** [comment]
Thanks for the report. How did you install ArrayFire? Where on your system is `libaf.so` installed? Can you compile programs using ArrayFire?

**Comment by theogrost** [comment]
Hi, thanks for reply!
I have done complete reinstallation of CUDA and ArrayFire. ArrayFire was built, and I am able to compile and run examples. I don't get libaf.so error anymore, but I keep getting this one: 
`** testing if installed package can be loaded
Error: package or namespace load failed for ‘RcppArrayFire’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/theogrost/R/x86_64-pc-linux-gnu-library/3.4/RcppArrayFire/libs/RcppArrayFire.so':
  /home/theogrost/R/x86_64-pc-linux-gnu-library/3.4/RcppArrayFire/libs/RcppArrayFire.so: undefined symbol: _ZN2af10infoStringEb
Error: loading failed
Execution halted
ERROR: loading failed`

I have custom installation directory of arrayfire, but for the purpose of testing I've installed it also in usr/local and tried installing RcppArrayFire without additional arguments, but result was the same :/

**Comment by rstub** [comment]
Do you install ArrayFire from source or using the binary installer?

**Comment by theogrost** [comment]
Source, in custom directory. But I also tried fresh install of Ubuntu with binary installed into /usr/local, with exact error. I am able to compile share/arrayfire/examples and project example (https://github.com/arrayfire/arrayfire-project-templates) and run them with no problems... Sorry to reply that late - but as I wrote, I was reinstalling whole system, but integration still doesn't work.

**Comment by rstub** [comment]
Ok, I will try to replicate this in a Docker image. Which version of R are you using? Which compiler (and version) are you using?

**Comment by theogrost** [comment]
R version is 3.4.3 and g++ is 5.4.0.20160609 - if that is info you need. Thanks!

**Comment by rstub** [comment]
I have two questions:

- Since `af::infoString` cannot be found on your system: What is the output of `readelf -sW /usr/local/lib/libaf.so | grep infoString`?
- So far I have successfully installed RcppArrayFire in a Docker container based on Ubuntu 16.04. One obvious difference is that there are no CUDA libraries in this container. How did you install CUDA libraries on your system?

For reference the used Docker file:
```
FROM ubuntu:16.04

RUN echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" >> /etc/apt/sources.list \
 && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9 \
 && apt-get update \
 && apt-get install --yes --no-install-recommends \
    r-base-dev \
    curl \
    libglfw3 \
    libgl1-mesa-glx \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && curl -o arrayfire-installer.sh  http://arrayfire.s3.amazonaws.com/3.5.1/ArrayFire-v3.5.1_Linux_x86_64.sh \
 && sh arrayfire-installer.sh --skip-license --exclude-subdir --prefix=/usr/local \
 && rm arrayfire-installer.sh \
 && ldconfig /usr/local/lib \
 && echo 'local({options(repos = "http://cran.rstudio.com/")})' >> /etc/R/Rprofile.site \
 && Rscript -e 'install.packages(c("codetools", "Rcpp", "drat", "pkgKitten", "knitr", "rmarkdown"))' \
 && Rscript -e 'drat::addRepo("RInstitute"); install.packages("RcppArrayFire")' \
 && rm -rf /tmp/*
```

**Comment by rstub** [comment]
Basing the docker image on `nvidia/cuda:8.0-runtime-ubuntu16.04` I was able to build RcppArrayFire with the above recipe.  However, according to the discussion in https://github.com/tensorflow/tensorflow/issues/4931 I probably won't be able to have a fully linked CUDA backend without CUDA hardware.

**Comment by rstub** [comment]
Can you please provide me with the output of `readelf -sW /usr/local/lib/libaf.so | grep infoString`? On my system it is
```
$ readelf -sW /usr/local/lib/libaf.so | grep infoString
  2394: 0000000000236b90   523 FUNC    GLOBAL DEFAULT   11 _ZN2af10infoStringEb
```

**Comment by theogrost** [comment]
Hi,
sorry for late reply. For given command I get:
```
4089: 0000000000229ab0   483 FUNC    GLOBAL DEFAULT   12 _ZN2af10infoStringEb
1883: 000000000028d020    33 OBJECT  LOCAL  DEFAULT   14 _ZZN2af10infoStringEbE19__PRETTY_FUNCTION__
4159: 0000000000229ab0   483 FUNC    GLOBAL DEFAULT   12 _ZN2af10infoStringEb
```

**Comment by rstub** [comment]
Thanks. I have found a bug in the `configure` script when `--with-arrayfire` is used. I am not sure if this is related to this issue, since I get slightly different errors. However, now installation also works for non-standard directories:
```
FROM ubuntu:16.04
MAINTAINER Ralf Stubner <ralf.stubner@r-institute.com>

RUN echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" >> /etc/apt/sources.list \
 && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9 \
 && apt-get update \
 && apt-get install --yes --no-install-recommends \
    r-base-dev \
    curl \
    libglfw3 \
    libgl1-mesa-glx \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && curl -o arrayfire-installer.sh  http://arrayfire.s3.amazonaws.com/3.5.1/ArrayFire-v3.5.1_Linux_x86_64.sh \
 && mkdir -p /opt/arrayfire-3 \
 && sh arrayfire-installer.sh --skip-license --exclude-subdir --prefix=/opt/arrayfire-3 \
 && rm arrayfire-installer.sh \
 && ldconfig /usr/local/lib \
 && echo 'local({options(repos = "http://cran.rstudio.com/")})' >> /etc/R/Rprofile.site \
 && Rscript -e 'install.packages(c("codetools", "Rcpp", "drat", "pkgKitten", "knitr", "rmarkdown"))' \
 && Rscript -e 'drat::addRepo("RInstitute"); install.packages("RcppArrayFire", configure.args = "--with-arrayfire=/opt/arrayfire-3")' \
 && rm -rf /tmp/*
```
Can you please try the new release v0.0.3?

**Comment by rstub** [comment]
BTW, installing v0.0.3 also works when compiling ArrayFire from source and installing it in a non-standard directory:
```
FROM ubuntu:16.04
MAINTAINER Ralf Stubner <ralf.stubner@r-institute.com>

RUN echo "deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" >> /etc/apt/sources.list \
 && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9 \
 && apt-get update \
 && apt-get install --yes --no-install-recommends \
    r-base-dev \
    build-essential git cmake libfreeimage-dev \
    libopenblas-dev libfftw3-dev liblapacke-dev \
    libglfw3-dev libfontconfig1-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && cd /tmp \
 && git clone --recursive https://github.com/arrayfire/arrayfire.git \
 && mkdir arrayfire/build \
 && cd arrayfire/build \
 && cmake .. -DCMAKE_INSTALL_PREFIX=/opt/arrayfire-3 \
 && make -j4 \
 && make install \
 && echo 'local({options(repos = "http://cran.rstudio.com/")})' >> /etc/R/Rprofile.site \
 && Rscript -e 'install.packages(c("codetools", "Rcpp", "drat", "pkgKitten", "knitr", "rmarkdown"))' \
 && Rscript -e 'drat::addRepo("RInstitute"); install.packages("RcppArrayFire", configure.args = "--with-arrayfire=/opt/arrayfire-3")' \
 && rm -rf /tmp/*
```
Within this container I get a similar result for the symbols within the library:
```
readelf -sW /opt/arrayfire-3/lib/libaf.so | grep infoString
  1082: 00000000007af481   627 FUNC    GLOBAL DEFAULT   12 _ZN2af10infoStringEb
  1999: 0000000000828ee0    33 OBJECT  LOCAL  DEFAULT   14 _ZZN2af10infoStringEbE19__PRETTY_FUNCTION__
  4107: 00000000007af481   627 FUNC    GLOBAL DEFAULT   12 _ZN2af10infoStringEb
```

**Comment by theogrost** [comment]
Hi,
thanks for updating - I was able to install package with custom ArrayFire directory and run pi example :)
So, I believe this can be closed. Thanks again!
